<a href="https://colab.research.google.com/github/harshith-118/MachineLearningProjects/blob/main/WineClassificationUsingNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
##from sklearn.neural_network import MLPClassifier

In [ ]:
names = ['Alcohol','Malic acid','Ash','Alcalinity of ash','Magnesium','Total phenols','Flavanoids','Nonflavanoid phenols','Proanthocyanins','Color intensity','Hue','OD280/OD315 of diluted wines','Proline','Class']
data = pd.read_csv("Wine1.csv",names=names)

In [ ]:
data.head()

Alcohol  Malic acid   Ash  ...  OD280/OD315 of diluted wines  Proline  Class
0    14.23        1.71  2.43  ...                          3.92     1065      1
1    13.20        1.78  2.14  ...                          3.40     1050      1
2    13.16        2.36  2.67  ...                          3.17     1185      1
3    14.37        1.95  2.50  ...                          3.45     1480      1
4    13.24        2.59  2.87  ...                          2.93      735      1

[5 rows x 14 columns]

In [ ]:
X = data.iloc[:, 0:13]
y = data.iloc[:, 13:]

In [ ]:
X.head()

Alcohol  Malic acid   Ash  ...   Hue  OD280/OD315 of diluted wines  Proline
0    14.23        1.71  2.43  ...  1.04                          3.92     1065
1    13.20        1.78  2.14  ...  1.05                          3.40     1050
2    13.16        2.36  2.67  ...  1.03                          3.17     1185
3    14.37        1.95  2.50  ...  0.86                          3.45     1480
4    13.24        2.59  2.87  ...  1.04                          2.93      735

[5 rows x 13 columns]

In [ ]:
y.head()

Class
0      1
1      1
2      1
3      1
4      1

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

y = y.apply(le.fit_transform)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='lbfgs',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
predictions = mlp.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[ 8  1  0]
 [ 0 17  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.94      1.00      0.97        17
           2       1.00      1.00      1.00        10

    accuracy                           0.97        36
   macro avg       0.98      0.96      0.97        36
weighted avg       0.97      0.97      0.97        36

0.9722222222222222
